def get_character_stats():
    stats = {
        "Level": "1",
        "-": "-",
        "Attacks per Second": "0",
        "Attack Speed %": "0%",
        "Movement Speed": "0",
        "Strength": "0",
        "Energy": "0",
        "Armor": "0",
        "Stamina": "0",
        "All Stats": "0",
        "All Talents": "0",
        "Damage": "0",
        "Attack Power": "0",
        "Ability Power": "0",
        "Critical Damage": "0",
        "Critical Chance": "0",
        "Physical Damage": "0",
        "Magic Damage": "0",
        "Wind Damage": "0",
        "Cold Damage": "0",
        "Fire Damage": "0",
        "Poison Damage": "0",
        "Lightning Damage": "0",
        "Elemental Damage": "0",
        "Max Health": "0",
        "Max Mana": "0",
        "Health Per Second": "0",
        "Mana Per Second": "0",
        "Life Per Hit": "0",
        "Mana Per Hit": "0",
        "Cooldown Reduction": "0",
        "Health After Kill": "0",
        "Mana After Kill": "0",
        "Exp Gain": "0",
        "Magic Find": "0",
        "Block Chance": "0",
        "Dodge": "0",
        "Reduction": "0",
        "Damage Return": "0",
        "All Resistances": "0",
        "Physical Resistances": "0",
        "Magic Resistances": "0",
        "Cold Resistances": "0",
        "Fire Resistances": "0",
        "Poison Resistances": "0",
        "Lightning Resistances": "0",
    }
    return stats


def amazon_stats():
    stats = {
        "Level": "1",
        "-": "-",
        "Attacks per Second": "0.85",
        "Attack Speed %": "0%",
        "Movement Speed": "35",
        "Strength": "11",
        "Energy": "7",
        "Armor": "1",
        "Stamina": "11",
        "All Stats": "0",
        "All Talents": "0",
        "Damage": "5",
        "Attack Power": "0",
        "Ability Power": "0",
        "Critical Damage": "25%",
        "Critical Chance": "5%",
        "Physical Damage": "0",
        "Magic Damage": "0",
        "Wind Damage": "0",
        "Cold Damage": "0",
        "Fire Damage": "0",
        "Poison Damage": "0",
        "Lightning Damage": "0",
        "Elemental Damage": "0",
        "Max Health": "28",
        "Max Mana": "14",
        "Health Per Second": "1",
        "Mana Per Second": "2",
        "Life Per Hit": "0",
        "Mana Per Hit": "0",
        "Cooldown Reduction": "0",
        "Health After Kill": "0",
        "Mana After Kill": "0",
        "Exp Gain": "0",
        "Magic Find": "10%",
        "Block Chance": "0",
        "Dodge": "0",
        "Reduction": "0",
        "Damage Return": "0",
        "All Resistances": "0",
        "Physical Resistances": "0",
        "Magic Resistances": "0",
        "Cold Resistances": "0",
        "Fire Resistances": "0",
        "Poison Resistances": "0",
        "Lightning Resistances": "0",
    }
    return stats