def shieldFunc():
    shieldList = {
        "-": "-",
        
        "Ancient Aegis": {
            "Attacks per Second": "0",
            "Attack Speed %": "0%",
            "Movement Speed": "0",
            "Strength": "0",
            "Energy": "612",
            "Armor": "2295",
            "Stamina": "765",
            "All Stats": "0",
            "All Talents": "0",
            "Damage": "0",
            "Attack Power": "0",
            "Ability Power": "0",
            "Critical Damage": "0",
            "Critical Chance": "0",
            "Physical Damage": "0",
            "Magic Damage": "0",
            "Wind Damage": "0",
            "Cold Damage": "0",
            "Fire Damage": "0",
            "Poison Damage": "0",
            "Lightning Damage": "0",
            "Elemental Damage": "0",
            "Max Health": "0",
            "Max Mana": "600",
            "Health Per Second": "0",
            "Mana Per Second": "0",
            "Life Per Hit": "0",
            "Mana Per Hit": "0",
            "Cooldown Reduction": "0",
            "Health After Kill": "0",
            "Mana After Kill": "0",
            "Exp Gain": "0",
            "Magic Find": "0",
            "Block Chance": "25%",
            "Dodge": "0",
            "Reduction": "0",
            "Damage Return": "0",
            "All Resistances": "0",
            "Physical Resistances": "12%",
            "Magic Resistances": "12%",
            "Cold Resistances": "0",
            "Fire Resistances": "0",
            "Poison Resistances": "0",
            "Lightning Resistances": "0",
        }       
    }
    return shieldList